openapi: 3.0.1
info:
  title: 驾途无忧
  description: 实时、智能的交通助手，可以导航、规划、查询路况和天气。
  version: "v1"
servers:
  - url: http://127.0.0.1:8104
paths:

  /route_planning:
    post:
      operationId: routePlanning
      summary: 根据用户给出的起始点、所在城市、交通方式、出行需求，进行路线规划，指导用户到达目的地
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/routePlanning"
      responses:
        "200":
          description: 路线规划成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/messageResponse"
      x-return-raw:
        description: 标记当前API请求的结果是否经过大模型，当name的值不空时，从插件结果中获取具体字段，类型必须string，直接返回，而不经过大模型。
        mediaType: application/json
        name: message
        type: string

  /get_image:
    post:
      operationId: getImage
      summary: 获取纸质火车票图片的URL地址，返回车票上的详情信息
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/getImage"
      responses:
        "200":
          description: 获取URL成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/messageResponse"
      x-return-raw:
        description: 标记当前API请求的结果是否经过大模型，当name的值不空时，从插件结果中获取具体字段，类型必须string，直接返回，而不经过大模型。
        mediaType: application/json
        name: message
        type: string

  /plan_trip:
    post:
      operationId: planTrip
      description: 帮助用户规划行程
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/routePlanning"
      responses:
        200:
          description: 插件信息返回成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/messageResponse"
      x-return-raw:
        description: 标记当前API请求的结果是否经过大模型，当name的值不空时，从插件结果中获取具体字段，类型必须string，直接返回，而不经过大模型。
        mediaType: application/json
        name: message
        type: string

  /get_description:
    post:
      operationId: getDescription
      description: 驾途无忧插件的信息
      responses:
        200:
          description: 插件信息返回成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/description"
components:
  schemas:
    description:
      type: object
      properties:
        pluginName:
          type: string
          description: 插件的名称
        pluginDescription:
          type: string
          description: 插件的介绍
        pluginUrl:
          type: string
          description: 插件的官网


    # 请求URL
    routePlanning:
      type: object
      # 必选字段
      required: [ region, origin, destination,way ]
      properties:
        # 字段名
        way:
          # 类型
          type: integer
          # 描述
          description: driving为0,riding为1,walking为2transit为3
        region:
          type: string
          description: 用户所在城市
        origin:
          type: string
          description: 起点地名
        destination:
          type: string
          description: 终点地名
        plateNumber:
          type: string
          description: 车牌号
        tactics:
          type: integer
          description: 0：时间最短1：不走高速,2：躲避拥堵,3：最短距离,4：花费最少,5：大路优先



    getImage:
      type: object
      required: [ url,userinput ]
      properties:
        url:
          type: string
          description: 图像的URL地址
        userinput:
          type: string
          description: URL地址以外的中文内容，例如“火车票的路径如下：”


    messageResponse:
      type: object
      required: [ message ]
      properties:
        code:
          type: integer
          description: 返回的代码,不是0就是有问题的
        data:
          type: object
          properties:
            message:
              type: string
              description: 各种交通相关的信息
            mapUrl:
              type: string
              description: 存放图片的url地址
                    
